---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-demo
  namespace: flux
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/ericsoucy/flux-demo

